# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  access_token_key: PIDC0aHQtNkcQhyIG2WCsdUD7/xC2Q==
  cache:
    ttl:
      short: <%= 1.hours %>
      long: <%= 1.hours %>
  instagram:
    id: 37ebd4b86f44498397c5fa1c524de751
    secret: ae853a177cc94a04a840ae2a96a9e2dc
  secret_key_base: 6ebb76c6fa31cbdeaaf4b3215ffef5c252af63d952e1c7e50822ed0a712378d6384116a11832cb32be92e1367b0509f0cb5164de9b0625fc40d173fa6eea831a
  test:
    instagram:
      access_token: 643071493.37ebd4b.27ecfbbd8b094e6eb77a77e55ac01f9c

test:
  access_token_key: <%= SecureRandom.base64(22) %>
  cache:
    short: <%= 1.hours %>
    long: <%= 1.hours %>
  instagram:
    id: 37ebd4b86f44498397c5fa1c524de751
    secret: ae853a177cc94a04a840ae2a96a9e2dc
  secret_key_base: c146700e27455af43125719896c9eb75a6649b6b7f269f898d4fa559c4ada9a3011ea1a210f41877da20b6ad043efa7caf45fdf9b7af6664dbaa2867238aa4a7
  test:
    instagram:
      access_token: 643071493.37ebd4b.27ecfbbd8b094e6eb77a77e55ac01f9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
